import { existsSync } from "node:fs";
import { join } from "node:path";

import {
  FileAuthManager,
  getProviderDefaultModel,
  isSupportedProvider,
  pickPreferredProvider,
} from "@obora-kit/agents";
import { OboraDatabase } from "@obora/database";
import { Command } from "commander";
import fs from "fs-extra";

import { CLIError } from "../errors.js";

// Default config template
const DEFAULT_CONFIG = `# obora-kit Configuration
# Generated by: obora init
# Docs: https://github.com/obora-labs/obora-kit

project:
  name: "my-project"
  version: "0.1.0"

settings:
  workflow: "simple"
  database:
    type: "local"  # local | postgres
    path: ".obora/data.db"
`;

// Minimal config generator - respects workflow choice
const createMinimalConfig = (workflow: string) => `# obora-kit Configuration (Minimal)
project:
  name: "my-project"
  version: "0.1.0"

settings:
  workflow: "${workflow}"
`;

const STANDARD_CONFIG = `# obora-kit Configuration (Standard)
# Generated by: obora init --workflow standard

project:
  name: "my-project"
  version: "0.1.0"
  description: ""

settings:
  workflow: "standard"
  database:
    type: "local"
    path: ".obora/data.db"
  
features:
  tracking: true
  archive: true
  dependencies: true
`;

function appendAuthAwareDefaults(configContent: string, provider?: string): string {
  if (!provider) {
    return configContent;
  }

  const model = getProviderDefaultModel(provider);
  if (!model) {
    return configContent;
  }

  return `${configContent}\ndefaults:\n  provider: ${provider}\n  model: ${model}\n`;
}

// Default workflow templates
const SIMPLE_WORKFLOW = `# Simple Workflow
# Minimal workflow for quick iteration

name: simple
version: "1.0"

description: "Minimal demo workflow"

steps:
  - name: implement
    agent: developer
  - name: test
    agent: reviewer
    depends_on: [implement]
  - name: done
    agent: planner
    depends_on: [test]
`;

const STANDARD_WORKFLOW = `# Standard Workflow
# Full development workflow with proper phases

name: standard
version: "1.0"

description: "Standard implementation workflow"

steps:
  - name: spec
    agent: architect
  - name: design
    agent: architect
    depends_on: [spec]
  - name: implement
    agent: developer
    depends_on: [design]
  - name: test
    agent: reviewer
    depends_on: [implement]
  - name: docs
    agent: planner
    depends_on: [test]
`;

// Valid workflow types
const VALID_WORKFLOWS = ["simple", "standard"] as const;
type WorkflowType = (typeof VALID_WORKFLOWS)[number];

interface InitOptions {
  force?: boolean;
  workflow?: string;
  minimal?: boolean;
}

/**
 * Validate workflow type
 */
function validateWorkflowType(workflow: string): WorkflowType {
  if (!VALID_WORKFLOWS.includes(workflow as WorkflowType)) {
    console.error(
      `Error: Invalid workflow type '${workflow}'. Valid options: ${VALID_WORKFLOWS.join(", ")}`
    );
    throw new CLIError(
      `Invalid workflow type '${workflow}'. Valid options: ${VALID_WORKFLOWS.join(", ")}`,
      1
    );
  }
  return workflow as WorkflowType;
}

export function createInitCommand(): Command {
  const cmd = new Command("init")
    .description("Initialize obora project")
    .option("-f, --force", "Overwrite existing .obora/ directory")
    .option("-w, --workflow <type>", "Workflow type: simple or standard", "simple")
    .option("-m, --minimal", "Initialize with minimal configuration")
    .action(async (options: InitOptions) => {
      await runInit(options);
    });

  return cmd;
}

async function runInit(options: InitOptions): Promise<void> {
  const cwd = process.cwd();
  const oboraDir = join(cwd, ".obora");

  // Validate workflow type
  const workflowType = validateWorkflowType(options.workflow || "simple");

  // Check if already initialized
  if (existsSync(oboraDir)) {
    if (!options.force) {
      console.error("Error: .obora/ already exists. Use --force to overwrite.");
      throw new CLIError(".obora/ already exists. Use --force to overwrite.", 2);
    }
    console.log("Removing existing .obora/ directory...");
    await fs.remove(oboraDir);
  }

  console.log("Initializing obora project...");

  // Create directory structure
  const dirs = [
    oboraDir,
    join(oboraDir, "workflows"),
    join(oboraDir, "features"),
    join(oboraDir, "archive"),
    join(oboraDir, "agents"),
  ];

  for (const dir of dirs) {
    await fs.ensureDir(dir);
    console.log(`  Created: ${dir.replace(cwd, ".")}`);
  }

  const authManager = new FileAuthManager();
  const providers = await authManager.listProviders();
  const preferredProvider = pickPreferredProvider(
    providers.map((item) => item.provider).filter(isSupportedProvider)
  );

  // Determine config content - respect workflow choice even with --minimal
  let configContent: string;
  if (options.minimal) {
    configContent = createMinimalConfig(workflowType);
  } else if (workflowType === "standard") {
    configContent = STANDARD_CONFIG;
  } else {
    configContent = DEFAULT_CONFIG;
  }

  configContent = appendAuthAwareDefaults(configContent, preferredProvider);

  // Write config.yaml
  const configPath = join(oboraDir, "config.yaml");
  await fs.writeFile(configPath, configContent, "utf-8");
  console.log(`  Created: .obora/config.yaml`);

  // Copy workflow template (workflowType already validated above)
  const workflowContent = workflowType === "standard" ? STANDARD_WORKFLOW : SIMPLE_WORKFLOW;
  const workflowPath = join(oboraDir, "workflows", `${workflowType}.yaml`);
  await fs.writeFile(workflowPath, workflowContent, "utf-8");
  console.log(`  Created: .obora/workflows/${workflowType}.yaml`);

  // Create .gitkeep files for empty directories
  await fs.writeFile(join(oboraDir, "features", ".gitkeep"), "", "utf-8");
  await fs.writeFile(join(oboraDir, "archive", ".gitkeep"), "", "utf-8");
  await fs.writeFile(join(oboraDir, "agents", ".gitkeep"), "", "utf-8");

  // Initialize DuckDB
  const db = new OboraDatabase(join(oboraDir, "obora.db"));
  await db.initialize();
  db.close();
  console.log("  Created: .obora/obora.db");

  console.log("");
  console.log("✓ obora project initialized successfully!");
  console.log("");
  console.log("Next steps:");
  console.log("  1. Edit .obora/config.yaml to configure your project");
  console.log("  2. Run 'obora new <feature-name>' to create a new feature");
  console.log("  3. Run 'obora status' to view project status");
}

export { runInit };
