import { existsSync } from "node:fs";
import { join } from "node:path";

import { Command } from "commander";
import fs from "fs-extra";

// Default config template
const DEFAULT_CONFIG = `# obora-kit Configuration
# Generated by: obora init
# Docs: https://github.com/obora-labs/obora-kit

project:
  name: "my-project"
  version: "0.1.0"

settings:
  workflow: "simple"
  database:
    type: "local"  # local | postgres
    path: ".obora/data.db"
`;

// Minimal config generator - respects workflow choice
const createMinimalConfig = (workflow: string) => `# obora-kit Configuration (Minimal)
project:
  name: "my-project"
  version: "0.1.0"

settings:
  workflow: "${workflow}"
`;

const STANDARD_CONFIG = `# obora-kit Configuration (Standard)
# Generated by: obora init --workflow standard

project:
  name: "my-project"
  version: "0.1.0"
  description: ""

settings:
  workflow: "standard"
  database:
    type: "local"
    path: ".obora/data.db"
  
features:
  tracking: true
  archive: true
  dependencies: true
`;

// Default workflow templates
const SIMPLE_WORKFLOW = `# Simple Workflow
# Minimal workflow for quick iteration

name: simple
version: "1.0"

stages:
  - name: develop
    tasks:
      - implement
      - test
  - name: complete
    tasks:
      - review
      - done
`;

const STANDARD_WORKFLOW = `# Standard Workflow
# Full development workflow with proper phases

name: standard
version: "1.0"

stages:
  - name: planning
    tasks:
      - spec
      - design
  - name: development
    tasks:
      - implement
      - test
  - name: review
    tasks:
      - code-review
      - qa
  - name: completion
    tasks:
      - docs
      - done
`;

// Valid workflow types
const VALID_WORKFLOWS = ["simple", "standard"] as const;
type WorkflowType = (typeof VALID_WORKFLOWS)[number];

interface InitOptions {
  force?: boolean;
  workflow?: string;
  minimal?: boolean;
}

/**
 * Validate workflow type
 */
function validateWorkflowType(workflow: string): WorkflowType {
  if (!VALID_WORKFLOWS.includes(workflow as WorkflowType)) {
    console.error(
      `Error: Invalid workflow type '${workflow}'. Valid options: ${VALID_WORKFLOWS.join(", ")}`
    );
    process.exit(1);
  }
  return workflow as WorkflowType;
}

export function createInitCommand(): Command {
  const cmd = new Command("init")
    .description("Initialize obora project")
    .option("-f, --force", "Overwrite existing .obora/ directory")
    .option("-w, --workflow <type>", "Workflow type: simple or standard", "simple")
    .option("-m, --minimal", "Initialize with minimal configuration")
    .action(async (options: InitOptions) => {
      await runInit(options);
    });

  return cmd;
}

async function runInit(options: InitOptions): Promise<void> {
  const cwd = process.cwd();
  const oboraDir = join(cwd, ".obora");

  // Validate workflow type
  const workflowType = validateWorkflowType(options.workflow || "simple");

  // Check if already initialized
  if (existsSync(oboraDir)) {
    if (!options.force) {
      console.error("Error: .obora/ already exists. Use --force to overwrite.");
      process.exit(2);
    }
    console.log("Removing existing .obora/ directory...");
    await fs.remove(oboraDir);
  }

  console.log("Initializing obora project...");

  // Create directory structure
  const dirs = [
    oboraDir,
    join(oboraDir, "workflows"),
    join(oboraDir, "features"),
    join(oboraDir, "archive"),
  ];

  for (const dir of dirs) {
    await fs.ensureDir(dir);
    console.log(`  Created: ${dir.replace(cwd, ".")}`);
  }

  // Determine config content - respect workflow choice even with --minimal
  let configContent: string;
  if (options.minimal) {
    configContent = createMinimalConfig(workflowType);
  } else if (workflowType === "standard") {
    configContent = STANDARD_CONFIG;
  } else {
    configContent = DEFAULT_CONFIG;
  }

  // Write config.yaml
  const configPath = join(oboraDir, "config.yaml");
  await fs.writeFile(configPath, configContent, "utf-8");
  console.log(`  Created: .obora/config.yaml`);

  // Copy workflow template (workflowType already validated above)
  const workflowContent = workflowType === "standard" ? STANDARD_WORKFLOW : SIMPLE_WORKFLOW;
  const workflowPath = join(oboraDir, "workflows", `${workflowType}.yaml`);
  await fs.writeFile(workflowPath, workflowContent, "utf-8");
  console.log(`  Created: .obora/workflows/${workflowType}.yaml`);

  // Create .gitkeep files for empty directories
  await fs.writeFile(join(oboraDir, "features", ".gitkeep"), "", "utf-8");
  await fs.writeFile(join(oboraDir, "archive", ".gitkeep"), "", "utf-8");

  console.log("");
  console.log("✓ obora project initialized successfully!");
  console.log("");
  console.log("Next steps:");
  console.log("  1. Edit .obora/config.yaml to configure your project");
  console.log("  2. Run 'obora new <feature-name>' to create a new feature");
  console.log("  3. Run 'obora status' to view project status");
}

export { runInit };
