/**
 * obora plan - Generate implementation plan using AI
 * @module @obora/cli/commands/plan
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { log } from "@obora/core";
import { Command } from "commander";
import fs from "fs-extra";

/**
 * Status file structure
 */
interface StatusFile {
  feature: {
    name: string;
    created_at: string;
    workflow: string;
  };
  status: string;
  progress: {
    current_stage: string;
    completed_stages: string[];
  };
  metadata: {
    last_updated: string;
    notes: string;
  };
}

/**
 * Plan options
 */
interface PlanOptions {
  dryRun?: boolean;
  agent?: string;
  model?: string;
}

/**
 * Read and parse status.yaml
 */
function readStatus(featurePath: string): StatusFile {
  const statusPath = join(featurePath, "status.yaml");
  if (!existsSync(statusPath)) {
    throw new Error(`Status file not found: ${statusPath}`);
  }

  const content = readFileSync(statusPath, "utf-8");
  // Simple YAML parser (enough for our structure)
  const lines = content.split("\n");
  const status: StatusFile = {
    feature: { name: "", created_at: "", workflow: "" },
    status: "pending",
    progress: { current_stage: "planning", completed_stages: [] },
    metadata: { last_updated: "", notes: "" },
  };

  let currentSection: keyof StatusFile | null = null;

  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed.startsWith("feature:")) {
      currentSection = "feature";
      continue;
    }
    if (trimmed.startsWith("status:")) {
      currentSection = "status";
      status.status = trimmed.split(":")[1]?.trim() || "pending";
      continue;
    }
    if (trimmed.startsWith("progress:")) {
      currentSection = "progress";
      continue;
    }
    if (trimmed.startsWith("metadata:")) {
      currentSection = "metadata";
      continue;
    }

    if (currentSection === "feature" && trimmed.startsWith("name:")) {
      status.feature.name = trimmed.split(":")[1]?.trim().replace(/"/g, "") || "";
    }
    if (currentSection === "feature" && trimmed.startsWith("created_at:")) {
      status.feature.created_at = trimmed.split(":")[1]?.trim().replace(/"/g, "") || "";
    }
    if (currentSection === "feature" && trimmed.startsWith("workflow:")) {
      status.feature.workflow = trimmed.split(":")[1]?.trim().replace(/"/g, "") || "";
    }
    if (currentSection === "progress" && trimmed.startsWith("current_stage:")) {
      status.progress.current_stage = trimmed.split(":")[1]?.trim() || "planning";
    }
    if (currentSection === "metadata" && trimmed.startsWith("last_updated:")) {
      status.metadata.last_updated = trimmed.split(":")[1]?.trim().replace(/"/g, "") || "";
    }
  }

  return status;
}

/**
 * Update status.yaml
 */
async function updateStatus(featurePath: string, updates: Partial<StatusFile>): Promise<void> {
  const statusPath = join(featurePath, "status.yaml");
  let content = readFileSync(statusPath, "utf-8");

  // Update fields
  if (updates.status !== undefined) {
    content = content.replace(/^status:.*$/m, `status: ${updates.status}`);
  }
  if (updates.metadata?.last_updated !== undefined) {
    const now = updates.metadata.last_updated;
    content = content.replace(/^ {2}last_updated:.*$/m, `  last_updated: "${now}"`);
  }

  await fs.writeFile(statusPath, content, "utf-8");
}

/**
 * Read proposal and design files
 */
function readFeatureDocs(featurePath: string): { proposal: string; design: string } {
  const proposalPath = join(featurePath, "proposal.md");
  const designPath = join(featurePath, "design.md");

  const proposal = existsSync(proposalPath)
    ? readFileSync(proposalPath, "utf-8")
    : "# No proposal\n";
  const design = existsSync(designPath) ? readFileSync(designPath, "utf-8") : "# No design\n";

  return { proposal, design };
}

/**
 * Generate plan using AI (placeholder for OpenClaw integration)
 * In production, this would call the main agent via OpenClaw API
 */
async function generatePlanWithAI(
  featureName: string,
  proposal: string,
  design: string,
  options: PlanOptions
): Promise<string> {
  log("Generating implementation plan with AI...");

  // Placeholder: In production, this would:
  // 1. Call OpenClaw API with Architect agent
  // 2. Pass proposal.md and design.md as context
  // 3. Receive generated plan
  // 4. Return the plan content

  const model = options.model || "claude-opus-4-5";
  const agent = options.agent || "architect";

  log(`  Model: ${model}`);
  log(`  Agent: ${agent}`);

  // Simulated AI response - in production this comes from the agent
  const simulatedPlan = `# Implementation Plan: ${featureName}

> Generated by: ${agent} (${model})
> Generated at: ${new Date().toISOString()}

## Overview

This plan outlines the implementation steps for ${featureName}.

## Architecture Decisions

| Decision | Rationale |
|----------|-----------|
| Use TypeScript | Type safety and tooling |
| Modular structure | Maintainability and testability |

## Implementation Tasks

### Phase 1: Setup

- [ ] Initialize project structure
- [ ] Configure build tools
- [ ] Set up testing framework

### Phase 2: Core Implementation

- [ ] Implement core feature
- [ ] Add error handling
- [ ] Write unit tests

### Phase 3: Integration

- [ ] Integrate with existing systems
- [ ] Add documentation
- [ ] Performance testing

## Dependencies

- node: >=18
- pnpm: >=8

## Estimated Timeline

- Phase 1: 1 day
- Phase 2: 3-5 days
- Phase 3: 1-2 days

## Notes

*This is a simulated plan. In production, the AI agent will generate a detailed plan based on the proposal and design documents.*
`;

  return simulatedPlan;
}

/**
 * Update tasks.md with plan content
 */
async function updateTasks(featurePath: string, planContent: string): Promise<void> {
  const tasksPath = join(featurePath, "tasks.md");
  const existingContent = existsSync(tasksPath) ? readFileSync(tasksPath, "utf-8") : "";

  // Check if tasks.md already has plan section
  const hasPlanSection = existingContent.includes("## Implementation Plan");

  if (hasPlanSection) {
    // Replace existing plan section
    const updated = existingContent.replace(/## Implementation Plan[\s\S]*(?=\n##|$)/, planContent);
    await fs.writeFile(tasksPath, updated, "utf-8");
    log("  Updated existing plan in tasks.md");
  } else {
    // Append plan to tasks.md
    const separator = existingContent ? "\n\n---\n\n" : "";
    const updated = existingContent + separator + planContent;
    await fs.writeFile(tasksPath, updated, "utf-8");
    log("  Appended plan to tasks.md");
  }
}

/**
 * Main plan command logic
 */
async function runPlan(featureName: string, options: PlanOptions): Promise<void> {
  const cwd = process.cwd();
  const oboraDir = join(cwd, ".obora");
  const featuresDir = join(oboraDir, "features");
  const featureDir = join(featuresDir, featureName);

  // Validate .obora exists
  if (!existsSync(oboraDir)) {
    console.error("Error: Not in an obora project. Run 'obora init' first.");
    process.exit(3);
  }

  // Validate feature exists
  if (!existsSync(featureDir)) {
    console.error(`Error: Feature '${featureName}' not found.`);
    console.error(`  Run 'obora new ${featureName}' to create it first.`);
    process.exit(1);
  }

  console.log(`Generating plan for: ${featureName}`);
  console.log("");

  // Read status file
  const status = readStatus(featureDir);
  log(`  Current status: ${status.status}`);
  log(`  Current stage: ${status.progress.current_stage}`);

  // Read feature documents
  const { proposal, design } = readFeatureDocs(featureDir);
  log(`  Read proposal.md (${proposal.length} chars)`);
  log(`  Read design.md (${design.length} chars)`);

  if (options.dryRun) {
    console.log("");
    console.log("Dry-run mode: would generate plan with the following context:");
    console.log(`  Feature: ${featureName}`);
    console.log(`  Proposal length: ${proposal.length} chars`);
    console.log(`  Design length: ${design.length} chars`);
    console.log(`  Agent: ${options.agent || "architect"}`);
    console.log(`  Model: ${options.model || "claude-opus-4-5"}`);
    return;
  }

  // Generate plan with AI
  console.log("");
  const planContent = await generatePlanWithAI(featureName, proposal, design, options);

  // Update tasks.md
  await updateTasks(featureDir, planContent);

  // Update status
  const now = new Date().toISOString();
  await updateStatus(featureDir, {
    status: "planned",
    metadata: { last_updated: now, notes: "" },
  });

  console.log("");
  console.log("✓ Plan generated successfully!");
  console.log("");
  console.log("Next steps:");
  console.log(`  1. Review .obora/features/${featureName}/tasks.md`);
  console.log(`  2. Run 'obora run ${featureName}' to start execution`);
}

/**
 * Create the plan command
 */
export function createPlanCommand(): Command {
  const cmd = new Command("plan")
    .description("Generate implementation plan using AI")
    .argument("<name>", "Feature name")
    .option("--dry-run", "Show what would be done without making changes")
    .option("-a, --agent <name>", "AI agent to use (default: architect)")
    .option("-m, --model <name>", "AI model to use (default: claude-opus-4-5)")
    .action(async (name: string, options: PlanOptions) => {
      await runPlan(name, options);
    });

  return cmd;
}

export { runPlan };
