/**
 * obora plan - Generate implementation plan using AI
 * @module @obora/cli/commands/plan
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import * as path from "node:path";

import { log } from "@obora/core";
import { createAdapterFromEnv } from "@obora-kit/agents";
import { Command } from "commander";
import fs from "fs-extra";
import yaml from "yaml";

import { CLIError } from "../errors.js";
import { validatePathComponent } from "../utils/path-utils.js";
import { type StatusFile, readStatus } from "../utils/status.js";

/**
 * Plan options
 */
interface PlanOptions {
  dryRun?: boolean;
  agent?: string;
  model?: string;
  feature?: string;
  signal?: AbortSignal;
}

interface PlanGenerationContext {
  featureName: string;
  proposal: string;
  design: string;
  model?: string;
}

/**
 * Detect feature name from current directory
 */
function detectFeatureName(): string | null {
  const cwd = process.cwd();

  // Check if we're in .obora/features/<feature> directory
  if (cwd.includes(join(".obora", "features"))) {
    const parts = cwd.split(join(".obora", "features"));
    if (parts.length > 1) {
      const featurePart = parts[1].split(path.sep)[1];
      if (featurePart) {
        return featurePart;
      }
    }
  }

  return null;
}

function findProjectRoot(startDir: string): string | null {
  let currentDir = startDir;

  while (true) {
    const oboraDir = join(currentDir, ".obora");
    if (existsSync(oboraDir)) {
      return currentDir;
    }

    const parentDir = dirname(currentDir);
    if (parentDir === currentDir) {
      return null;
    }

    currentDir = parentDir;
  }
}

/**
 * Update status.yaml using YAML
 */
async function updateStatus(featurePath: string, updates: Partial<StatusFile>): Promise<void> {
  const statusPath = join(featurePath, "status.yaml");
  const content = readFileSync(statusPath, "utf-8");

  try {
    const parsed = yaml.parse(content) as Record<string, any>;

    if (updates.status !== undefined) {
      parsed.status = updates.status;
    }
    if (updates.metadata?.last_updated !== undefined) {
      if (!parsed.metadata) parsed.metadata = {};
      parsed.metadata.last_updated = updates.metadata.last_updated;
    }
    if (updates.metadata?.notes !== undefined) {
      if (!parsed.metadata) parsed.metadata = {};
      parsed.metadata.notes = updates.metadata.notes;
    }

    await fs.writeFile(statusPath, yaml.stringify(parsed), "utf-8");
  } catch (error) {
    // If YAML parsing fails, try regex-based update as fallback
    let newContent = content;
    if (updates.status !== undefined) {
      newContent = newContent.replace(/^status:.*$/m, `status: ${updates.status}`);
    }
    if (updates.metadata?.last_updated !== undefined) {
      const now = updates.metadata.last_updated;
      newContent = newContent.replace(/^ {2}last_updated:.*$/m, `  last_updated: "${now}"`);
    }
    await fs.writeFile(statusPath, newContent, "utf-8");
  }
}

/**
 * Read proposal and design files
 */
function readFeatureDocs(featurePath: string): { proposal: string; design: string } {
  const proposalPath = join(featurePath, "proposal.md");
  const designPath = join(featurePath, "design.md");

  const proposal = existsSync(proposalPath)
    ? readFileSync(proposalPath, "utf-8")
    : "# No proposal\n";
  const design = existsSync(designPath) ? readFileSync(designPath, "utf-8") : "# No design\n";

  return { proposal, design };
}

function normalizePlanMarkdown(
  generatedContent: string,
  model: string,
  agent: string,
  featureName: string
): string {
  const content = generatedContent.trim();
  if (content.includes("## Implementation Plan")) {
    return content;
  }

  return `## Implementation Plan\n\n> Generated by: ${agent} (${model})\n> Generated at: ${new Date().toISOString()}\n> Feature: ${featureName}\n\n${content}`;
}

function createPlanAbortSignal(timeoutMs: number, upstream?: AbortSignal): AbortSignal {
  const timeoutSignal = AbortSignal.timeout(timeoutMs);
  return upstream ? AbortSignal.any([upstream, timeoutSignal]) : timeoutSignal;
}

/**
 * Generate plan using AI via configured LLM adapter.
 */
async function generatePlanWithAI(
  context: PlanGenerationContext,
  options: PlanOptions
): Promise<string> {
  log("Generating implementation plan with AI...");

  const model = context.model || options.model || "pi-mono-1";
  const agent = options.agent || "architect";
  const llm = createAdapterFromEnv();

  log(`  Model: ${model}`);
  log(`  Agent: ${agent}`);
  log(`  Adapter: ${llm.id}`);

  const systemPrompt =
    "You are an expert software architect and project planner. " +
    "Given a feature proposal and design document, generate a detailed implementation plan " +
    "with phases, tasks, dependencies, and estimates. Output in Markdown format.";

  const userPrompt = [
    `## Feature: ${context.featureName}`,
    "",
    "### Proposal",
    context.proposal,
    "",
    "### Design",
    context.design,
    "",
    "Generate a comprehensive implementation plan.",
  ].join("\n");

  const timeoutMs = 120_000;

  try {
    const response = await llm.chatCompletion(
      {
        model,
        temperature: 0.2,
        maxTokens: 4096,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
      },
      { signal: createPlanAbortSignal(timeoutMs, options.signal) }
    );

    const generated = response.message.content?.trim();
    if (!generated) {
      throw new CLIError("[E5102] LLM returned empty plan content.", 1);
    }

    return normalizePlanMarkdown(generated, response.model || model, agent, context.featureName);
  } catch (error) {
    if (error instanceof CLIError) {
      throw error;
    }

    if (error instanceof Error && error.name === "AbortError") {
      throw new CLIError("[E5101] Plan generation timed out or was aborted.", 1);
    }

    throw new CLIError(`[E5100] Failed to generate plan with LLM: ${String(error)}`, 1);
  }
}

/**
 * Update tasks.md with plan content
 */
async function updateTasks(featurePath: string, planContent: string): Promise<void> {
  const tasksPath = join(featurePath, "tasks.md");
  const existingContent = existsSync(tasksPath) ? readFileSync(tasksPath, "utf-8") : "";

  // Check if tasks.md already has plan section
  const hasPlanSection = existingContent.includes("## Implementation Plan");

  if (hasPlanSection) {
    // Replace existing plan section
    const updated = existingContent.replace(/## Implementation Plan[\s\S]*?(?=\n## |$)/, planContent);
    await fs.writeFile(tasksPath, updated, "utf-8");
    log("  Updated existing plan in tasks.md");
  } else {
    // Append plan to tasks.md
    const separator = existingContent ? "\n\n---\n\n" : "";
    const updated = existingContent + separator + planContent;
    await fs.writeFile(tasksPath, updated, "utf-8");
    log("  Appended plan to tasks.md");
  }
}

/**
 * Main plan command logic
 */
async function runPlan(featureName: string, options: PlanOptions): Promise<void> {
  const cwd = process.cwd();
  const projectRoot = findProjectRoot(cwd);

  if (!projectRoot) {
    console.error("Error: Not in an obora project. Run 'obora init' first.");
    throw new CLIError("Not in an obora project. Run 'obora init' first.", 3);
  }

  const oboraDir = join(projectRoot, ".obora");
  const featureDir = join(oboraDir, "features", featureName);

  // Validate feature name for path traversal
  validatePathComponent(featureName);

  // Validate feature exists
  if (!existsSync(featureDir)) {
    console.error(`Error: Feature '${featureName}' not found.`);
    console.error(`  Run 'obora new ${featureName}' to create it first.`);
    throw new CLIError(`Feature '${featureName}' not found.`, 1);
  }

  console.log(`Generating plan for: ${featureName}`);
  console.log("");

  // Read status file
  const status = readStatus(featureDir);
  if (!status) {
    console.error(`Error: Status file not found for feature '${featureName}'.`);
    throw new CLIError(`Status file not found for feature '${featureName}'.`, 1);
  }
  log(`  Current status: ${status.status}`);
  log(`  Current stage: ${status.progress.current_stage}`);

  // Read feature documents
  const { proposal, design } = readFeatureDocs(featureDir);
  log(`  Read proposal.md (${proposal.length} chars)`);
  log(`  Read design.md (${design.length} chars)`);

  if (options.dryRun) {
    console.log("");
    console.log("Dry-run mode: would generate plan with the following context:");
    console.log(`  Feature: ${featureName}`);
    console.log(`  Proposal length: ${proposal.length} chars`);
    console.log(`  Design length: ${design.length} chars`);
    console.log(`  Agent: ${options.agent || "architect"}`);
    console.log(`  Model: ${options.model || "pi-mono-1"}`);
    return;
  }

  // Generate plan with AI
  console.log("");
  const planContent = await generatePlanWithAI(
    {
      featureName,
      proposal,
      design,
      model: options.model,
    },
    options
  );

  // Update tasks.md
  await updateTasks(featureDir, planContent);

  // Update status
  const now = new Date().toISOString();
  await updateStatus(featureDir, {
    status: "planned",
    metadata: { last_updated: now, notes: "" },
  });

  console.log("");
  console.log("✓ Plan generated successfully!");
  console.log("");
  console.log("Next steps:");
  console.log(`  1. Review .obora/features/${featureName}/tasks.md`);
  console.log(`  2. Run 'obora run ${featureName}' to start execution`);
}

/**
 * Create the plan command
 */
export function createPlanCommand(): Command {
  const cmd = new Command("plan")
    .description("Generate implementation plan using AI")
    .option("-f, --feature <name>", "Feature name")
    .option("--dry-run", "Show what would be done without making changes")
    .option("-a, --agent <name>", "AI agent to use (default: architect)")
    .option("-m, --model <name>", "AI model to use (default: pi-mono-1)")
    .action(async (options: PlanOptions) => {
      // Detect feature if not specified
      const featureName = options.feature || detectFeatureName();
      if (!featureName) {
        console.error("Error: Feature name required.");
        console.error("  Specify with --feature or run from within a feature directory.");
        throw new CLIError(
          "Feature name required. Specify with --feature or run from within a feature directory.",
          1
        );
      }
      await runPlan(featureName, options);
    });

  return cmd;
}

export { runPlan };
export type { PlanGenerationContext };
