/**
 * Drizzle Database Connection (Next.js + SQLite)
 * Auto-generated by: obora add drizzle
 */

import Database from "better-sqlite3";
import type { Database as DatabaseType } from "better-sqlite3";
import { drizzle, BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema";

// ============================================================================
// Configuration
// ============================================================================

const DATABASE_URL = process.env.DATABASE_URL || "file:./db.sqlite";
const dbPath = DATABASE_URL.startsWith("file:") ? DATABASE_URL.slice(5) : DATABASE_URL;

// ============================================================================
// Singleton
// ============================================================================

let sqlite: DatabaseType | null = null;
let drizzleDb: BetterSQLite3Database<typeof schema> | null = null;

// ============================================================================
// Database
// ============================================================================

/**
 * Get Drizzle database instance
 *
 * @example
 * ```typescript
 * import { db } from "@/lib/db";
 * import { users } from "@/lib/schema";
 *
 * const allUsers = db.select().from(users).all();
 * ```
 */
export function getDb(): BetterSQLite3Database<typeof schema> {
  if (drizzleDb) return drizzleDb;

  sqlite = new Database(dbPath);
  sqlite.pragma("journal_mode = WAL");
  drizzleDb = drizzle(sqlite, { schema });

  return drizzleDb;
}

/** Database instance */
export const db = getDb();

/** Close connection */
export function closeDb(): void {
  if (sqlite) {
    sqlite.close();
    sqlite = null;
    drizzleDb = null;
  }
}

export type DrizzleDb = BetterSQLite3Database<typeof schema>;
