/**
 * obora done - Mark feature as done and archive
 * @module @obora/cli/commands/done
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import * as path from "node:path";

import { log } from "@obora/core";
import { Command } from "commander";
import fs from "fs-extra";
import yaml from "yaml";

import { CLIError } from "../../errors.js";
import { validatePathComponent } from "../../utils/path-utils.js";
import { type StatusFile, readStatus } from "../../utils/status.js";

/**
 * Workflow run record from DuckDB
 */
interface WorkflowRun {
  id: string;
  feature_name: string;
  workflow_name: string;
  started_at: string;
  completed_at?: string;
  status: string;
  total_steps: number;
  completed_steps: number;
}

/**
 * Done options
 */
interface DoneOptions {
  commit?: boolean;
  message?: string;
  noArchive?: boolean;
  dryRun?: boolean;
  feature?: string;
}

/**
 * Detect feature name from current directory
 */
function detectFeatureName(): string | null {
  const cwd = process.cwd();

  // Check if we're in .obora/features/<feature> directory
  if (cwd.includes(join(".obora", "features"))) {
    const parts = cwd.split(join(".obora", "features"));
    if (parts.length > 1) {
      const featurePart = parts[1].split(path.sep)[1];
      if (featurePart) {
        return featurePart;
      }
    }
  }

  return null;
}

/**
 * Get workflow runs from DuckDB (placeholder)
 */
async function getWorkflowRuns(featureName: string): Promise<WorkflowRun[]> {
  log(`  [DuckDB] Querying workflow runs for ${featureName}...`);

  // Placeholder: In production, this would query DuckDB
  return [
    {
      id: "run-1738617600000",
      feature_name: featureName,
      workflow_name: "simple",
      started_at: "2026-02-04T00:00:00Z",
      completed_at: "2026-02-04T00:05:00Z",
      status: "completed",
      total_steps: 4,
      completed_steps: 4,
    },
  ];
}

/**
 * Update workflow run status in DuckDB (placeholder)
 */
async function updateWorkflowRunStatus(runId: string, status: string): Promise<void> {
  log(`  [DuckDB] Updating run ${runId} status to ${status}...`);
  // Placeholder: In production, this would update DuckDB
}

/**
 * Generate execution log content
 */
function generateExecutionLog(status: StatusFile, runs: WorkflowRun[]): string {
  const lines: string[] = [];

  lines.push(`# Execution Log: ${status.feature.name}`);
  lines.push("");
  lines.push(`> Feature: ${status.feature.name}`);
  lines.push(`> Workflow: ${status.feature.workflow}`);
  lines.push(`> Created: ${status.feature.created_at}`);
  lines.push(`> Completed: ${new Date().toISOString()}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`Final Status: ${status.status}`);
  lines.push(`Current Stage: ${status.progress.current_stage}`);
  lines.push(`Completed Stages: ${status.progress.completed_stages.join(", ") || "none"}`);
  lines.push("");

  if (runs.length > 0) {
    lines.push("## Workflow Runs");
    lines.push("");

    for (const run of runs) {
      lines.push(`### Run: ${run.id}`);
      lines.push("");
      lines.push(`- Workflow: ${run.workflow_name}`);
      lines.push(`- Started: ${run.started_at}`);
      lines.push(`- Completed: ${run.completed_at || "N/A"}`);
      lines.push(`- Status: ${run.status}`);
      lines.push(`- Progress: ${run.completed_steps}/${run.total_steps} steps`);
      lines.push("");
    }
  }

  lines.push("## Artifacts");
  lines.push("");
  lines.push("- [ ] proposal.md");
  lines.push("- [ ] design.md");
  lines.push("- [ ] tasks.md");
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("*Generated by obora done*");

  return lines.join("\n");
}

/**
 * Write execution log
 */
async function writeExecutionLog(featurePath: string, content: string): Promise<void> {
  const logPath = join(featurePath, "execution.log");
  await fs.writeFile(logPath, content, "utf-8");
}

/**
 * Move feature to archive
 */
async function moveToArchive(
  featuresDir: string,
  archiveDir: string,
  featureName: string
): Promise<void> {
  const sourcePath = join(featuresDir, featureName);

  // Generate archive name: YYYY-MM-featureName
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const archiveName = `${year}-${month}-${featureName}`;
  const targetPath = join(archiveDir, archiveName);

  // Ensure archive directory exists
  await fs.ensureDir(archiveDir);

  // Check if target already exists
  if (existsSync(targetPath)) {
    // Add timestamp suffix
    const timestamp = Date.now();
    const timestampedPath = join(archiveDir, `${archiveName}-${timestamp}`);
    await fs.move(sourcePath, timestampedPath, { overwrite: true });
    log(`  Moved to archive as ${archiveName}-${timestamp}`);
  } else {
    await fs.move(sourcePath, targetPath, { overwrite: true });
    log(`  Moved to archive as ${archiveName}`);
  }
}

/**
 * Update status to done using YAML
 */
async function updateStatusToDone(featurePath: string): Promise<void> {
  const statusPath = join(featurePath, "status.yaml");
  const content = readFileSync(statusPath, "utf-8");

  try {
    const parsed = yaml.parse(content) as Record<string, any>;
    parsed.status = "completed";
    await fs.writeFile(statusPath, yaml.stringify(parsed), "utf-8");
  } catch (error) {
    // If YAML parsing fails, try regex-based update as fallback
    const newContent = content.replace(/^status:.*$/m, `status: completed`);
    await fs.writeFile(statusPath, newContent, "utf-8");
  }
}

/**
 * Create git commit (placeholder)
 * In production, this would use git commands
 */
async function createGitCommit(featureName: string, message?: string): Promise<void> {
  log(`  [Git] Creating commit for ${featureName}...`);

  // Placeholder: In production, this would:
  // 1. git add the feature directory
  // 2. git commit with message
  // 3. Return commit hash

  const commitMessage = message || `feat: complete ${featureName}`;
  log(`    Commit message: ${commitMessage}`);
  // Simulated commit hash
  return;
}

/**
 * Validate feature can be marked as done
 */
function validateFeatureDone(status: StatusFile): { valid: boolean; reason?: string } {
  // Check if already done
  if (status.status === "completed") {
    return { valid: false, reason: "Feature is already marked as done" };
  }

  // Check if still running
  if (status.status === "running") {
    return {
      valid: false,
      reason: "Feature is still running. Use 'obora run' to check progress or wait for completion.",
    };
  }

  // Check if failed
  if (status.status === "failed") {
    return {
      valid: false,
      reason: "Feature workflow failed. Fix issues and re-run before marking as done.",
    };
  }

  return { valid: true };
}

/**
 * Main done command logic
 */
async function runDone(featureName: string, options: DoneOptions): Promise<void> {
  const cwd = process.cwd();
  const oboraDir = join(cwd, ".obora");
  const featuresDir = join(oboraDir, "features");
  const archiveDir = join(oboraDir, "archive");
  const featureDir = join(featuresDir, featureName);

  // Validate feature name for path traversal
  validatePathComponent(featureName);

  // Validate .obora exists
  if (!existsSync(oboraDir)) {
    console.error("Error: Not in an obora project. Run 'obora init' first.");
    throw new CLIError("Not in an obora project. Run 'obora init' first.", 3);
  }

  // Validate feature exists
  if (!existsSync(featureDir)) {
    console.error(`Error: Feature '${featureName}' not found.`);
    throw new CLIError(`Feature '${featureName}' not found.`, 1);
  }

  console.log(`Marking feature as done: ${featureName}`);
  console.log("");

  // Read status
  const status = readStatus(featureDir);
  if (!status) {
    console.error(`Error: Status file not found for feature '${featureName}'.`);
    throw new CLIError(`Status file not found for feature '${featureName}'.`, 1);
  }

  log(`  Current status: ${status.status}`);
  log(`  Current stage: ${status.progress.current_stage}`);

  // Validate can be marked as done
  const validation = validateFeatureDone(status);
  if (!validation.valid) {
    console.error(`Error: ${validation.reason}`);
    throw new CLIError(validation.reason || "Cannot mark feature as done", 1);
  }

  // Get workflow runs from DuckDB
  const runs = await getWorkflowRuns(featureName);
  log(`  Found ${runs.length} workflow run(s)`);

  if (options.dryRun) {
    console.log("");
    console.log("Dry-run mode: would perform the following actions:");
    console.log(`  1. Update status to 'completed'`);
    console.log(`  2. Generate execution.log`);
    if (!options.noArchive) {
      console.log(`  3. Move to archive/`);
    }
    if (options.commit) {
      console.log(`  4. Create git commit`);
    }
    return;
  }

  // Update status to done
  console.log("Updating status...");
  await updateStatusToDone(featureDir);

  // Generate execution log
  console.log("Generating execution log...");
  const logContent = generateExecutionLog(status, runs);
  await writeExecutionLog(featureDir, logContent);

  // Update workflow run status in DuckDB
  if (runs.length > 0) {
    await updateWorkflowRunStatus(runs[0].id, "completed");
  }

  // Move to archive
  if (!options.noArchive) {
    console.log("Moving to archive...");
    await moveToArchive(featuresDir, archiveDir, featureName);
  }

  // Create git commit
  if (options.commit) {
    console.log("Creating git commit...");
    await createGitCommit(featureName, options.message);
  }

  console.log("");
  console.log("✓ Feature marked as done successfully!");
  console.log("");
  console.log("Summary:");
  console.log(`  Feature: ${featureName}`);
  console.log(`  Status: completed`);
  console.log(`  Workflow runs: ${runs.length}`);
  if (!options.noArchive) {
    console.log(`  Archived: yes`);
  }
  if (options.commit) {
    console.log(`  Git commit: ${options.message || `feat: complete ${featureName}`}`);
  }
  console.log("");
  console.log("The feature is ready for review and deployment.");
}

/**
 * Create the done command
 */
export function createDoneCommand(): Command {
  const cmd = new Command("done")
    .description("Mark feature as done and archive")
    .option("-f, --feature <name>", "Feature name")
    .option("-c, --commit", "Create git commit after archiving")
    .option("-m, --message <text>", "Git commit message")
    .option("--no-archive", "Skip moving to archive directory")
    .option("--dry-run", "Show what would be done without making changes")
    .action(async (options: DoneOptions) => {
      // Detect feature if not specified
      const featureName = options.feature || detectFeatureName();
      if (!featureName) {
        console.error("Error: Feature name required.");
        console.error("  Specify with --feature or run from within a feature directory.");
        throw new CLIError(
          "Feature name required. Specify with --feature or run from within a feature directory.",
          1
        );
      }
      await runDone(featureName, options);
    });

  return cmd;
}

export { runDone };
