import { existsSync } from "node:fs";
import { join } from "node:path";

import { Command } from "commander";
import fs from "fs-extra";
import yaml from "yaml";

import { CLIError } from "../../errors.js";
import { validatePathComponent } from "../../utils/path-utils.js";

// Reserved words that cannot be used as feature names
const RESERVED_WORDS = [
  "init",
  "new",
  "plan",
  "run",
  "status",
  "done",
  "validate",
  "lock",
  "config",
];

// Valid workflow types
const VALID_WORKFLOWS = ["simple", "standard"] as const;
type WorkflowType = (typeof VALID_WORKFLOWS)[number];

// Templates
const PROPOSAL_TEMPLATE = (name: string, date: string) => `# ${name} - 기획서 (Proposal)

> 생성일: ${date}
> 상태: draft

## 목표

<!-- 이 피처가 달성하고자 하는 목표를 작성하세요 -->

## 배경

<!-- 왜 이 피처가 필요한지 배경을 설명하세요 -->

## 요구사항

### 기능 요구사항

- [ ] 요구사항 1
- [ ] 요구사항 2

### 비기능 요구사항

- [ ] 성능
- [ ] 보안

## 범위

### 포함

- 포함 항목 1
- 포함 항목 2

### 제외

- 제외 항목 1

## 참고 자료

- [관련 문서](link)
`;

const DESIGN_TEMPLATE = (name: string, date: string) => `# ${name} - 설계서 (Design)

> 생성일: ${date}
> 상태: draft

## 아키텍처

<!-- 전체 아키텍처 설명 -->

## 컴포넌트

### 컴포넌트 1

- 역할:
- 책임:

## 데이터 모델

\`\`\`typescript
// 데이터 모델 정의
\`\`\`

## API 설계

### Endpoint 1

- Method: GET
- Path: /api/v1/example
- Request:
- Response:

## 시퀀스 다이어그램

\`\`\`mermaid
sequenceDiagram
    participant A as Actor
    participant B as System
    A->>B: Request
    B-->>A: Response
\`\`\`

## 결정 사항

| 결정 | 이유 | 대안 |
|------|------|------|
| 결정 1 | 이유 1 | 대안들 |

## 참고 자료

- [관련 문서](link)
`;

const TASKS_TEMPLATE = (name: string, date: string) => `# ${name} - 작업 목록 (Tasks)

> 생성일: ${date}
> 상태: pending

## 작업 목록

### Phase 1: 기획 (Planning)

- [ ] 요구사항 정의
- [ ] 기획서 작성 (proposal.md)

### Phase 2: 설계 (Design)

- [ ] 아키텍처 설계
- [ ] 설계서 작성 (design.md)

### Phase 3: 구현 (Implementation)

- [ ] 구현 작업 1
- [ ] 구현 작업 2
- [ ] 테스트 작성

### Phase 4: 완료 (Completion)

- [ ] 코드 리뷰
- [ ] 문서화
- [ ] 배포

## 완료 조건

- [ ] 모든 테스트 통과
- [ ] 코드 리뷰 승인
- [ ] 문서 업데이트 완료
`;

const STATUS_TEMPLATE = (
  name: string,
  date: string,
  workflow: string,
  description: string
) => {
  const status = {
    feature: {
      name,
      description,
      created_at: date,
      workflow,
    },
    status: "pending", // pending | running | completed | failed | blocked | paused | cancelled
    progress: {
      current_stage: "planning",
      completed_stages: [] as string[],
    },
    metadata: {
      last_updated: date,
      notes: "",
    },
  };

  return `# Status file for feature: ${name}\n# Generated by: obora new\n\n${yaml.stringify(status)}`;
};

const CONTEXT_README_TEMPLATE = (name: string) => `# Context Directory

This directory stores contextual information and assets for the **${name}** feature.

## Purpose

The \`context/\` folder contains:

- **Reference materials**: Links to relevant documentation, specs, or external resources
- **Draft notes**: Temporary notes, brainstorming, or scratchpad content
- **Supporting files**: Any additional files that help understand or implement the feature

## Usage

- Store files here that provide context but aren't part of the main deliverables
- This folder is **not** included in the final feature archive
- Use \`proposal.md\`, \`design.md\`, and \`tasks.md\` for formal documentation

## Examples

\`\`\`
context/
├── reference-links.md     # External documentation links
├── brainstorming.md        # Initial ideas and notes
├── screenshots/            # UI mockups or reference images
└── api-examples.json       # Sample API responses
\`\`\`
`;

interface NewOptions {
  workflow?: string;
  fromExisting?: boolean;
  template?: string;
  description?: string;
}

/* YAML serialization is handled by yaml.stringify in STATUS_TEMPLATE */

/**
 * Validate workflow type
 */
function validateWorkflowType(workflow: string): WorkflowType {
  if (!VALID_WORKFLOWS.includes(workflow as WorkflowType)) {
    console.error(
      `Error: Invalid workflow type '${workflow}'. Valid options: ${VALID_WORKFLOWS.join(", ")}`
    );
    throw new CLIError(
      `Invalid workflow type '${workflow}'. Valid options: ${VALID_WORKFLOWS.join(", ")}`,
      1
    );
  }
  return workflow as WorkflowType;
}

/**
 * Validate feature name
 * - Only lowercase letters, numbers, and hyphens
 * - Max 64 characters
 * - Cannot start or end with hyphen
 * - No consecutive hyphens
 * - Not a reserved word
 * - No path traversal characters
 */
function validateFeatureName(name: string): { valid: boolean; error?: string } {
  // Check for path traversal (security)
  try {
    validatePathComponent(name);
  } catch (err) {
    return {
      valid: false,
      error: err instanceof Error ? err.message : "Invalid feature name",
    };
  }

  // Check reserved words
  if (RESERVED_WORDS.includes(name.toLowerCase())) {
    return {
      valid: false,
      error: `'${name}' is a reserved word and cannot be used as a feature name`,
    };
  }

  // Check length
  if (name.length === 0) {
    return { valid: false, error: "Feature name cannot be empty" };
  }

  if (name.length > 64) {
    return {
      valid: false,
      error: "Feature name cannot exceed 64 characters",
    };
  }

  // Check format: only lowercase letters, numbers, hyphens
  if (!/^[a-z0-9-]+$/.test(name)) {
    return {
      valid: false,
      error: "Feature name must contain only lowercase letters, numbers, and hyphens (kebab-case)",
    };
  }

  // Check start/end characters
  if (name.startsWith("-") || name.endsWith("-")) {
    return {
      valid: false,
      error: "Feature name cannot start or end with a hyphen",
    };
  }

  // Check consecutive hyphens
  if (name.includes("--")) {
    return {
      valid: false,
      error: "Feature name cannot contain consecutive hyphens",
    };
  }

  return { valid: true };
}

export function createNewCommand(): Command {
  const cmd = new Command("new")
    .description("Create new feature")
    .argument("<name>", "Feature name (kebab-case)")
    .option("-w, --workflow <type>", "Workflow to use", "simple")
    .option("--from-existing", "Start from existing documents (Brownfield)")
    .option("-t, --template <name>", "Template to use")
    .option("-d, --description <text>", "Feature description")
    .action(async (name: string, options: NewOptions) => {
      await runNew(name, options);
    });

  return cmd;
}

async function runNew(name: string, options: NewOptions): Promise<void> {
  const cwd = process.cwd();
  const oboraDir = join(cwd, ".obora");
  const featuresDir = join(oboraDir, "features");
  const featureDir = join(featuresDir, name);
  const archiveDir = join(oboraDir, "archive");

  // Check if .obora/ exists
  if (!existsSync(oboraDir)) {
    console.error("Error: Not in an obora project. Run 'obora init' first.");
    throw new CLIError("Not in an obora project. Run 'obora init' first.", 3);
  }

  // Validate feature name
  const validation = validateFeatureName(name);
  if (!validation.valid) {
    console.error(`Error: ${validation.error}`);
    throw new CLIError(validation.error || "Invalid feature name", 1);
  }

  // Check for duplicate feature
  if (existsSync(featureDir)) {
    console.error(`Error: Feature '${name}' already exists.`);
    throw new CLIError(`Feature '${name}' already exists.`, 1);
  }

  // Warn if archived feature with same name exists
  const archivedFeature = join(archiveDir, name);
  if (existsSync(archivedFeature)) {
    console.warn(
      `Warning: An archived feature with name '${name}' exists. Consider using a different name.`
    );
  }

  const now = new Date().toISOString().split("T")[0]; // YYYY-MM-DD
  const description = options.description?.trim() || "";
  // Validate and use workflow type
  const workflow = validateWorkflowType(options.workflow || "simple");

  console.log(`Creating feature: ${name}`);

  // Create directory structure
  await fs.ensureDir(featureDir);
  await fs.ensureDir(join(featureDir, "context"));

  // Create files
  const proposal = description
    ? `${PROPOSAL_TEMPLATE(name, now)}\n## 한 줄 설명\n\n${description}\n`
    : PROPOSAL_TEMPLATE(name, now);
  await fs.writeFile(join(featureDir, "proposal.md"), proposal, "utf-8");
  console.log(`  Created: .obora/features/${name}/proposal.md`);

  await fs.writeFile(join(featureDir, "design.md"), DESIGN_TEMPLATE(name, now), "utf-8");
  console.log(`  Created: .obora/features/${name}/design.md`);

  await fs.writeFile(join(featureDir, "tasks.md"), TASKS_TEMPLATE(name, now), "utf-8");
  console.log(`  Created: .obora/features/${name}/tasks.md`);

  await fs.writeFile(
    join(featureDir, "status.yaml"),
    STATUS_TEMPLATE(name, now, workflow, description),
    "utf-8"
  );
  console.log(`  Created: .obora/features/${name}/status.yaml`);

  await fs.writeFile(join(featureDir, "context", ".gitkeep"), "", "utf-8");
  console.log(`  Created: .obora/features/${name}/context/`);

  await fs.writeFile(
    join(featureDir, "context", "README.md"),
    CONTEXT_README_TEMPLATE(name),
    "utf-8"
  );
  console.log(`  Created: .obora/features/${name}/context/README.md`);

  if (options.fromExisting) {
    console.log("");
    console.log("Note: --from-existing mode enabled.");
    console.log("  → Edit proposal.md to import your existing documentation");
  }

  console.log("");
  console.log(`✓ Feature '${name}' created successfully!`);
  console.log("");
  console.log("Next steps:");
  console.log(`  1. Edit .obora/features/${name}/proposal.md to define requirements`);
  console.log(`  2. Run 'obora plan ${name}' to generate implementation plan`);
  console.log(`  3. Run 'obora run ${name}' to start development`);
}

export { runNew, validateFeatureName };
