/**
 * Drizzle Database Connection
 * Auto-generated by obora add drizzle-nextjs
 */

import Database from "better-sqlite3";
import type { Database as DatabaseType } from "better-sqlite3";
import { drizzle, BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema";

// ============================================================================
// Configuration
// ============================================================================

const DATABASE_URL = process.env.DATABASE_URL || "file:./db.sqlite";

// Extract file path from SQLite URL
const dbPath = DATABASE_URL.startsWith("file:")
  ? DATABASE_URL.slice(5)
  : DATABASE_URL;

// ============================================================================
// Singleton
// ============================================================================

let sqliteInstance: DatabaseType | null = null;
let drizzleInstance: BetterSQLite3Database<typeof schema> | null = null;

// ============================================================================
// Database Connection
// ============================================================================

/**
 * Get Drizzle database instance (singleton)
 *
 * @example
 * ```typescript
 * import { db } from "@/lib/db";
 * import { users } from "@/lib/schema";
 *
 * const allUsers = db.select().from(users).all();
 * ```
 */
export function getDb(): BetterSQLite3Database<typeof schema> {
  if (drizzleInstance) {
    return drizzleInstance;
  }

  sqliteInstance = new Database(dbPath);
  sqliteInstance.pragma("journal_mode = WAL");

  drizzleInstance = drizzle(sqliteInstance, { schema });
  return drizzleInstance;
}

/**
 * Database instance for direct imports
 */
export const db = getDb();

/**
 * Close database connection
 */
export function closeDb(): void {
  if (sqliteInstance) {
    sqliteInstance.close();
    sqliteInstance = null;
    drizzleInstance = null;
  }
}

export type DrizzleDb = BetterSQLite3Database<typeof schema>;
