/**
 * Drizzle Schema
 * Auto-generated by obora add drizzle-nextjs
 *
 * Define your database tables here.
 * @see https://orm.drizzle.team/docs/sql-schema-declaration
 */

import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

// ============================================================================
// Example: Users Table
// ============================================================================

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name"),
  createdAt: text("created_at").notNull().default("datetime('now')"),
  updatedAt: text("updated_at").notNull().default("datetime('now')"),
});

// Type exports
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

// ============================================================================
// Add your tables below
// ============================================================================

// export const posts = sqliteTable("posts", {
//   id: text("id").primaryKey(),
//   title: text("title").notNull(),
//   content: text("content"),
//   authorId: text("author_id").references(() => users.id),
//   createdAt: text("created_at").notNull().default("datetime('now')"),
// });
