#!/usr/bin/env bash
# Reddit-like Design Document Generation PoC
# Usage: bash run-design-demo.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OBORA="node ${SCRIPT_DIR}/../../bin/obora.js"
cd "$SCRIPT_DIR"

echo "═══════════════════════════════════════════"
echo "  Obora Reddit Design-Doc Generation PoC"
echo "═══════════════════════════════════════════"
echo ""

# ─── 1. Status check ───
echo "▶ Step 1: obora status -d"
$OBORA status -d 2>&1 || true
echo ""

# ─── 2. Validate workflow ───
echo "▶ Step 2: Validate workflow"
$OBORA validate 2>&1 || true
echo ""

# ─── 3. Run workflow (simulate — generate docs from templates + requirements) ───
echo "▶ Step 3: Run design-doc generation workflow"
FEATURE="reddit-design"
$OBORA run --feature "$FEATURE" 2>&1 || {
  echo "  ⚠ obora run not fully wired yet — falling back to local generation"
}
echo ""

# ─── 4. Generate documents locally ───
echo "▶ Step 4: Generate design documents"
mkdir -p output

REQ_FILE="input/requirements.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# --- PRD.md ---
cat > output/PRD.md << PRDDOC
# Product Requirements Document: Reddit-like Service

> Generated by Obora Design-Doc Workflow
> Source: ${REQ_FILE}
> Generated: ${TIMESTAMP}

## 1. Product Overview

A simplified Reddit-like community platform enabling users to create posts,
comment in nested threads, vote on content, and discover trending topics
through a hot-ranking algorithm.

## 2. Target Users

- Community members seeking topic-based discussions
- Content creators sharing links and text posts
- Moderators managing subreddit communities

## 3. Core Features

### 3.1 Posts (P0)
| Field | Type | Required |
|-------|------|----------|
| title | string(300) | ✅ |
| body | text | ❌ |
| url | string | ❌ |
| author_id | uuid | ✅ |
| subreddit_id | uuid | ✅ |
| created_at | timestamp | ✅ |

- CRUD operations with soft-delete
- Text posts and link posts

### 3.2 Comments (P0)
- Nested tree structure (max depth: 10)
- Parent reference for threading
- Soft-delete preserving tree structure

### 3.3 Voting (P0)
- Upvote / downvote toggle per user per item
- Applies to both posts and comments
- Separate tally table for query performance

### 3.4 Hot Ranking (P1)
- Algorithm: \`score = log10(max(|ups - downs|, 1)) + sign(ups - downs) * seconds / 45000\`
- Recalculated every 5 minutes via background job
- Cached in Redis sorted set

### 3.5 Subreddits (P1)
- Create, subscribe, unsubscribe
- Moderator roles
- Custom rules per subreddit

### 3.6 Users & Auth (P0)
- Email + password registration
- JWT-based authentication
- Karma score derived from votes received

## 4. Non-Functional Requirements

| Requirement | Target |
|-------------|--------|
| Concurrent users | 10K |
| API p95 latency | < 200ms |
| Primary DB | PostgreSQL 16 |
| Cache | Redis 7 |
| API style | REST (OpenAPI 3.1) |
| Deployment | Docker Compose (dev) / K8s (prod) |

## 5. Out of Scope (MVP)
- Real-time notifications / WebSocket
- Media uploads / CDN
- Moderation queue
- Full-text search

## 6. Success Metrics
- Post creation latency < 100ms (p95)
- Feed load < 200ms (p95)
- Vote processing < 50ms (p95)
PRDDOC

echo "  ✓ output/PRD.md"

# --- Architecture.md ---
cat > output/Architecture.md << 'ARCHDOC'
# Architecture Document: Reddit-like Service

> Generated by Obora Design-Doc Workflow

## 1. System Overview

```
┌──────────┐     ┌──────────────┐     ┌────────────┐
│  Client   │────▶│  API Gateway │────▶│  App Server │
│ (SPA/App) │     │  (nginx)     │     │  (Node.js)  │
└──────────┘     └──────────────┘     └─────┬──────┘
                                            │
                              ┌─────────────┼─────────────┐
                              ▼             ▼             ▼
                        ┌──────────┐  ┌──────────┐  ┌──────────┐
                        │PostgreSQL│  │  Redis    │  │ Worker   │
                        │  (data)  │  │ (cache/   │  │ (ranking │
                        │          │  │  ranking) │  │  cron)   │
                        └──────────┘  └──────────┘  └──────────┘
```

## 2. Tech Stack

| Layer | Technology | Rationale |
|-------|-----------|-----------|
| API Server | Node.js + Fastify | High throughput, TypeScript native |
| Database | PostgreSQL 16 | ACID, JSONB, proven at scale |
| Cache | Redis 7 | Sorted sets for ranking, session cache |
| Auth | JWT + bcrypt | Stateless, horizontally scalable |
| Container | Docker Compose / K8s | Dev/prod parity |

## 3. Data Model

### posts
| Column | Type | Notes |
|--------|------|-------|
| id | uuid | PK |
| title | varchar(300) | NOT NULL |
| body | text | nullable |
| url | varchar(2048) | nullable |
| author_id | uuid | FK → users |
| subreddit_id | uuid | FK → subreddits |
| created_at | timestamptz | DEFAULT now() |
| deleted_at | timestamptz | soft delete |

### comments
| Column | Type | Notes |
|--------|------|-------|
| id | uuid | PK |
| body | text | NOT NULL |
| author_id | uuid | FK → users |
| post_id | uuid | FK → posts |
| parent_id | uuid | FK → comments (nullable) |
| depth | int | max 10 |
| created_at | timestamptz | |

### votes
| Column | Type | Notes |
|--------|------|-------|
| user_id | uuid | PK (composite) |
| target_id | uuid | PK (composite) |
| target_type | enum | 'post' / 'comment' |
| value | int | +1 or -1 |
| created_at | timestamptz | |

### vote_tallies
| Column | Type | Notes |
|--------|------|-------|
| target_id | uuid | PK |
| target_type | enum | |
| ups | int | |
| downs | int | |
| score | float | hot score |

## 4. Key Design Decisions

1. **Separate vote_tallies table** — avoids COUNT aggregation on every feed load
2. **Redis sorted set for hot feed** — O(log N) insert, O(log N + M) range query
3. **Comment depth limit (10)** — prevents pathological nesting, simplifies recursive CTE
4. **Soft delete** — preserves thread structure when posts/comments are removed

## 5. Scaling Strategy

- **Read replicas** for PostgreSQL (feed reads)
- **Redis Cluster** for ranking cache
- **Horizontal app server scaling** behind load balancer
- **Background worker** for ranking recalculation (decoupled from request path)
ARCHDOC

echo "  ✓ output/Architecture.md"

# --- API-Spec.md ---
cat > output/API-Spec.md << 'APIDOC'
# API Specification: Reddit-like Service

> Generated by Obora Design-Doc Workflow
> Style: REST (OpenAPI 3.1 compatible)

## Base URL
```
https://api.example.com/v1
```

## Authentication
All mutating endpoints require `Authorization: Bearer <JWT>`.

---

## Endpoints

### Posts

| Method | Path | Description | Auth |
|--------|------|-------------|------|
| GET | /posts | List posts (paginated, sorted) | ❌ |
| GET | /posts/:id | Get single post | ❌ |
| POST | /posts | Create post | ✅ |
| PATCH | /posts/:id | Update post | ✅ (owner) |
| DELETE | /posts/:id | Soft-delete post | ✅ (owner/mod) |

#### GET /posts
Query params:
- `subreddit` (string) — filter by subreddit name
- `sort` (enum: hot | new | top) — default: hot
- `limit` (int, 1-100) — default: 25
- `cursor` (string) — pagination cursor

Response: `200 OK`
```json
{
  "data": [
    {
      "id": "uuid",
      "title": "string",
      "body": "string|null",
      "url": "string|null",
      "author": { "id": "uuid", "username": "string" },
      "subreddit": "string",
      "votes": { "up": 10, "down": 2, "score": 8 },
      "comment_count": 5,
      "created_at": "ISO8601"
    }
  ],
  "cursor": "string|null"
}
```

#### POST /posts
```json
{
  "title": "string (required, max 300)",
  "body": "string (optional)",
  "url": "string (optional)",
  "subreddit_id": "uuid (required)"
}
```
Response: `201 Created`

### Comments

| Method | Path | Description | Auth |
|--------|------|-------------|------|
| GET | /posts/:id/comments | List comments (tree) | ❌ |
| POST | /posts/:id/comments | Create comment | ✅ |
| PATCH | /comments/:id | Update comment | ✅ (owner) |
| DELETE | /comments/:id | Soft-delete comment | ✅ (owner/mod) |

#### GET /posts/:id/comments
Query params:
- `sort` (enum: best | new | old) — default: best
- `depth` (int, 0-10) — max nesting depth to return

### Votes

| Method | Path | Description | Auth |
|--------|------|-------------|------|
| PUT | /votes | Cast or change vote | ✅ |
| DELETE | /votes/:target_id | Remove vote | ✅ |

#### PUT /votes
```json
{
  "target_id": "uuid",
  "target_type": "post|comment",
  "value": 1 | -1
}
```
Response: `200 OK` — returns updated tally

### Subreddits

| Method | Path | Description | Auth |
|--------|------|-------------|------|
| GET | /subreddits | List subreddits | ❌ |
| GET | /subreddits/:name | Get subreddit | ❌ |
| POST | /subreddits | Create subreddit | ✅ |
| POST | /subreddits/:name/subscribe | Subscribe | ✅ |
| DELETE | /subreddits/:name/subscribe | Unsubscribe | ✅ |

### Users & Auth

| Method | Path | Description | Auth |
|--------|------|-------------|------|
| POST | /auth/register | Register | ❌ |
| POST | /auth/login | Login (returns JWT) | ❌ |
| GET | /users/me | Current user profile | ✅ |
| GET | /users/:username | Public profile | ❌ |

---

## Error Format
```json
{
  "error": {
    "code": "VALIDATION_ERROR",
    "message": "Title is required",
    "details": [...]
  }
}
```

## Rate Limits
- Anonymous: 60 req/min
- Authenticated: 300 req/min
- Write endpoints: 30 req/min
APIDOC

echo "  ✓ output/API-Spec.md"

# --- Task-Breakdown.md ---
cat > output/Task-Breakdown.md << 'TASKDOC'
# Task Breakdown: Reddit-like Service

> Generated by Obora Design-Doc Workflow

## Sprint 1: Foundation (Week 1-2)

### T-001: Project Setup
- [ ] Initialize Node.js + Fastify project
- [ ] Configure TypeScript, ESLint, Prettier
- [ ] Docker Compose: PostgreSQL + Redis
- [ ] CI pipeline (lint, test, build)
- **Estimate:** 4h | **Priority:** P0

### T-002: Database Schema & Migrations
- [ ] Create migration tool setup (node-pg-migrate)
- [ ] Users table
- [ ] Subreddits table
- [ ] Posts table
- [ ] Comments table (with depth constraint)
- [ ] Votes + vote_tallies tables
- [ ] Indexes for common queries
- **Estimate:** 6h | **Priority:** P0

### T-003: Auth Module
- [ ] POST /auth/register (bcrypt hash)
- [ ] POST /auth/login (JWT issue)
- [ ] Auth middleware (JWT verify)
- [ ] GET /users/me
- **Estimate:** 6h | **Priority:** P0

## Sprint 2: Core CRUD (Week 3-4)

### T-004: Posts CRUD
- [ ] POST /posts (create)
- [ ] GET /posts/:id (read)
- [ ] PATCH /posts/:id (update, owner check)
- [ ] DELETE /posts/:id (soft-delete)
- [ ] GET /posts (list, pagination, cursor)
- **Estimate:** 8h | **Priority:** P0

### T-005: Comments CRUD
- [ ] POST /posts/:id/comments (with depth check)
- [ ] GET /posts/:id/comments (recursive CTE tree)
- [ ] PATCH /comments/:id
- [ ] DELETE /comments/:id (soft-delete, preserve tree)
- **Estimate:** 8h | **Priority:** P0

### T-006: Voting System
- [ ] PUT /votes (upsert vote)
- [ ] DELETE /votes/:target_id
- [ ] Trigger: update vote_tallies on vote change
- [ ] Unit tests for edge cases (double vote, toggle)
- **Estimate:** 6h | **Priority:** P0

## Sprint 3: Ranking & Subreddits (Week 5-6)

### T-007: Hot Ranking
- [ ] Background worker (node-cron, 5-min interval)
- [ ] Reddit hot algorithm implementation
- [ ] Redis sorted set for ranked feed
- [ ] GET /posts?sort=hot reads from Redis
- **Estimate:** 6h | **Priority:** P1

### T-008: Subreddits
- [ ] CRUD for subreddits
- [ ] Subscribe / unsubscribe
- [ ] Feed filtering by subscription
- [ ] Moderator role (basic)
- **Estimate:** 8h | **Priority:** P1

### T-009: Integration Testing & Hardening
- [ ] End-to-end API tests
- [ ] Rate limiting middleware
- [ ] Error handling standardization
- [ ] Logging (pino)
- **Estimate:** 6h | **Priority:** P1

## Summary

| Sprint | Tasks | Total Estimate |
|--------|-------|---------------|
| Sprint 1 | T-001 ~ T-003 | 16h |
| Sprint 2 | T-004 ~ T-006 | 22h |
| Sprint 3 | T-007 ~ T-009 | 20h |
| **Total** | **9 tasks** | **58h** |
TASKDOC

echo "  ✓ output/Task-Breakdown.md"

# --- ADR.md ---
cat > output/ADR.md << 'ADRDOC'
# Architecture Decision Records: Reddit-like Service

> Generated by Obora Design-Doc Workflow

---

## ADR-001: Use Separate Vote Tallies Table

**Status:** Accepted
**Date:** 2026-02-14

### Context
Counting votes on every feed query (SELECT COUNT(*) GROUP BY) is O(N) and
becomes a bottleneck as vote volume grows.

### Decision
Maintain a `vote_tallies` table with pre-aggregated `ups`, `downs`, and `score`.
Update via database trigger or application-level write-through on each vote.

### Consequences
- ✅ Feed queries read pre-computed values — O(1) per post
- ✅ Simple cache invalidation (single row update)
- ⚠️ Slight write amplification (extra UPDATE on each vote)
- ⚠️ Potential race condition — mitigated with `UPDATE ... SET ups = ups + 1`

---

## ADR-002: Redis Sorted Set for Hot Ranking

**Status:** Accepted
**Date:** 2026-02-14

### Context
Hot ranking requires sorting all posts by a time-decaying score.
PostgreSQL ORDER BY on a computed column is viable but slow at scale.

### Decision
Store hot scores in a Redis sorted set (`ZADD hot:<subreddit> score post_id`).
Background worker recalculates every 5 minutes.

### Consequences
- ✅ O(log N) insert and O(log N + M) range query
- ✅ Subreddit-scoped feeds via separate keys
- ⚠️ Eventual consistency (up to 5-min staleness)
- ⚠️ Redis memory usage grows with post count

---

## ADR-003: Comment Depth Limit of 10

**Status:** Accepted
**Date:** 2026-02-14

### Context
Unlimited nesting creates complex recursive queries and deep UI rendering issues.

### Decision
Enforce max depth of 10 at the application level.
Comments at depth 10 can still be created but force `parent_id = depth-10 ancestor`.

### Consequences
- ✅ Bounded recursive CTE depth — predictable query performance
- ✅ Simpler frontend rendering
- ⚠️ Deep discussions may feel constrained

---

## ADR-004: JWT for Authentication (No Session Store)

**Status:** Accepted
**Date:** 2026-02-14

### Context
Session-based auth requires a shared session store (Redis/DB), adding a
dependency to every authenticated request.

### Decision
Use short-lived JWT (15 min) + refresh token (7 days, stored in DB).
Stateless verification on the app server.

### Consequences
- ✅ Horizontally scalable — no shared session state
- ✅ Simple middleware implementation
- ⚠️ Token revocation requires a blocklist (Redis TTL set)
- ⚠️ JWT payload size adds ~500 bytes per request
ADRDOC

echo "  ✓ output/ADR.md"

echo ""

# ─── 5. Verify outputs ───
echo "▶ Step 5: Verify generated documents"
echo ""
DOCS=(PRD.md Architecture.md API-Spec.md Task-Breakdown.md ADR.md)
ALL_OK=true
for doc in "${DOCS[@]}"; do
  if [ -f "output/$doc" ]; then
    SIZE=$(wc -c < "output/$doc" | tr -d ' ')
    LINES=$(wc -l < "output/$doc" | tr -d ' ')
    echo "  ✓ output/$doc  (${LINES} lines, ${SIZE} bytes)"
  else
    echo "  ✗ output/$doc  MISSING"
    ALL_OK=false
  fi
done

echo ""
echo "═══════════════════════════════════════════"
if $ALL_OK; then
  echo "  ✓ All 5 design documents generated successfully"
else
  echo "  ✗ Some documents failed to generate"
fi
echo "═══════════════════════════════════════════"
