export enum OboraErrorCode {
  CELL_TIMEOUT = "CELL_1001",
  CELL_TOOL_DENIED = "CELL_1002",
  CELL_LLM_ERROR = "CELL_1003",
  CELL_ABORTED = "CELL_1004",

  POLICY_DENY = "POLICY_2001",
  POLICY_GATE_REQUIRED = "POLICY_2002",
  POLICY_GATE_TIMEOUT = "POLICY_2003",
  POLICY_GATE_REJECTED = "POLICY_2004",
  POLICY_SANDBOX_VIOLATION = "POLICY_2005",
  POLICY_RESOURCE_EXCEEDED = "POLICY_2006",
  POLICY_LOAD_FAILED = "POLICY_2007",

  CONSENSUS_FAIL = "CONSENSUS_3001",
  CONSENSUS_TIMEOUT = "CONSENSUS_3002",
  CONSENSUS_QUORUM_NOT_MET = "CONSENSUS_3003",

  RECOVERY_RETRY_EXHAUSTED = "RECOVERY_4001",
  RECOVERY_ROLLBACK_FAILED = "RECOVERY_4002",
  RECOVERY_ESCALATION_TIMEOUT = "RECOVERY_4003",

  ORCH_WORKFLOW_NOT_FOUND = "ORCH_5001",
  ORCH_STEP_NOT_FOUND = "ORCH_5002",
  ORCH_DEPENDENCY_FAILED = "ORCH_5003",
  ORCH_EXECUTION_TIMEOUT = "ORCH_5004",

  AUDIT_STORE_ERROR = "AUDIT_6001",
  AUDIT_REPLAY_NOT_FOUND = "AUDIT_6002",

  ADAPTER_LLM_UNAVAILABLE = "ADAPTER_7001",
  ADAPTER_AUTH_FAILED = "ADAPTER_7002",
  ADAPTER_TOOL_NOT_FOUND = "ADAPTER_7003",
}
