/**
 * Todo Type Definition
 * 
 * Based on: docs/10-architecture.md (Section 4)
 * - id: string (timestamp + random suffix for collision prevention)
 * - text: string (task content, max 1000 characters)
 * - completed: boolean (completion status)
 */

export interface Todo {
  /** Unique identifier generated by timestamp + random suffix */
  id: string;
  
  /** Task content (max 1000 characters, trimmed) */
  text: string;
  
  /** Completion status */
  completed: boolean;
}

/**
 * Filter type for todo list
 * 
 * Based on: docs/10-architecture.md (Section 4.3)
 */
export type Filter = 'all' | 'active' | 'completed';

/**
 * Todo state structure
 * 
 * Based on: docs/10-architecture.md (Section 4.1)
 */
export interface TodoState {
  /** Array of todos */
  todos: Todo[];
  
  /** Current filter state */
  filter: Filter;
}

/**
 * Action types for state management
 * 
 * Based on: docs/10-architecture.md (Section 4.4)
 */
export type TodoAction =
  | { type: 'ADD_TODO'; payload: { text: string } }
  | { type: 'TOGGLE_TODO'; payload: { id: string } }
  | { type: 'DELETE_TODO'; payload: { id: string } }
  | { type: 'SET_FILTER'; payload: { filter: Filter } }
  | { type: 'LOAD_STATE'; payload: TodoState }
  | { type: 'CLEAR_COMPLETED' };

/**
 * Filtered todos with counts
 */
export interface FilteredTodos {
  /** Filtered todo list */
  todos: Todo[];
  
  /** Count of all todos */
  all: number;
  
  /** Count of active todos */
  active: number;
  
  /** Count of completed todos */
  completed: number;
}

/**
 * LocalStorage keys
 * 
 * Based on: docs/10-architecture.md (Section 6.1)
 */
export const STORAGE_KEYS = {
  TODOS: 'todo-app-todos',
  FILTER: 'todo-app-filter',
} as const;

/**
 * Validation error types
 */
export type ValidationError =
  | 'EMPTY_INPUT'
  | 'TOO_LONG';

/**
 * Error messages
 */
export const ERROR_MESSAGES: Record<ValidationError, string> = {
  EMPTY_INPUT: '태스크 내용을 입력해주세요.',
  TOO_LONG: '태스크 내용은 1000자 이하여야 합니다.',
} as const;
