/**
 * Minimal custom pattern plugin example for Obora.
 *
 * This file intentionally stays framework-agnostic so it can be copied
 * into your own project and adapted to your runtime wiring.
 */
export const customSummaryPlugin = {
  name: "custom-summary",
  version: "1.0.0",
  type: "pattern",
  async execute(context: { input?: unknown; config?: { style?: string; max_points?: number } }) {
    const style = context.config?.style ?? "concise";
    const maxPoints = context.config?.max_points ?? 5;

    return {
      success: true,
      output: {
        summary: `Generated by custom-summary plugin (style=${style}, max_points=${maxPoints}).`,
      },
    };
  },
};

export default customSummaryPlugin;
